import { PostResponse } from "./types";
const dimension = {
  height: "100vh",
  width: "1250px",
};
export const tags: string[] = [
  "dummy tags1",
  "dummy tags2",
  "dummy tags3",
  "dummy tags1",
  "dummy tags2",
  "dummy tags3",
  "dummy tags1",
  "dummy tags2",
  "dummy tags3",
  "dummy tags1",
  "dummy tags2",
  "dummy tags3",
  "dummy tags1",
  "dummy tags2",
  "dummy tags3",
  "dummy tags1",
  "dummy tags2",
  "dummy tags3",
];
export const posts: PostResponse[] = [
  {
    title: "dummy title1",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title2",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
  {
    title: "dummy title",
    summary: "dummy summary",
    tags: ["dummy tags1", "dummy tags2", "dummy tags3"],
    date: "2024/04/14",
  },
];
